name: Build & Publish Biogent Image


on:
push:
branches: [ main ]
paths:
- 'Containerfile'
- 'entrypoint.sh'
- '.github/workflows/build.yml'
workflow_dispatch: {}


jobs:
build:
runs-on: ubuntu-latest
permissions:
contents: read
packages: write
steps:
- name: Checkout
uses: actions/checkout@v4


- name: Set up QEMU
uses: docker/setup-qemu-action@v3


- name: Set up Buildx
uses: docker/setup-buildx-action@v3


- name: Login to GHCR
uses: docker/login-action@v3
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}


- name: Build & Push
uses: docker/build-push-action@v6
with:
context: .
file: ./Containerfile
platforms: linux/amd64
push: true
tags: |
ghcr.io/omegabappa/biogent:latest
ghcr.io/omegabappa/biogent:${{ github.sha }}
